Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.urbondo.PrintApiGatewayRequest
      CodeUri: /Users/menabebawy/Documents/repos/UrbondoInfrastructure/lambda
      Runtime: java17
      Architectures:
        - x86_64